[2025-07-16T17:20:04.296+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T17:20:04.529+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-15T00:00:00+00:00 [queued]>
[2025-07-16T17:20:04.571+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-15T00:00:00+00:00 [queued]>
[2025-07-16T17:20:04.574+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-07-16T17:20:04.643+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_insert_data_to_json> on 2025-06-15 00:00:00+00:00
[2025-07-16T17:20:04.780+0000] {standard_task_runner.py:72} INFO - Started process 185 to run task
[2025-07-16T17:20:04.976+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'scrape_and_insert_data_to_json', 'scheduled__2025-06-15T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpze0zn5rr']
[2025-07-16T17:20:05.014+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask scrape_and_insert_data_to_json
[2025-07-16T17:20:05.321+0000] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-15T00:00:00+00:00 [running]> on host 569ba507bc01
[2025-07-16T17:20:05.683+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='scrape_and_insert_data_to_json' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-15T00:00:00+00:00'
[2025-07-16T17:20:05.693+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-16T17:20:05.697+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-16T17:20:05.702+0000] {logging_mixin.py:190} INFO - Current task name:scrape_and_insert_data_to_json state:running start_date:2025-07-16 17:20:04.532078+00:00
[2025-07-16T17:20:05.707+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-07-16T17:20:05.713+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-16T17:20:05.722+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-07-16T17:20:08.749+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:20:09.556+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:20:09.817+0000] {logger.py:11} INFO - There is no [linux64] chromedriver "138.0.7204.157" for browser google-chrome "138.0.7204" in cache
[2025-07-16T17:20:09.822+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:20:10.049+0000] {job.py:229} INFO - Heartbeat recovered after 16.68 seconds
[2025-07-16T17:20:12.220+0000] {logger.py:11} INFO - WebDriver version 138.0.7204.157 selected
[2025-07-16T17:20:12.241+0000] {logger.py:11} INFO - Modern chrome version https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.157/linux64/chromedriver-linux64.zip
[2025-07-16T17:20:12.244+0000] {logger.py:11} INFO - About to download new driver from https://storage.googleapis.com/chrome-for-testing-public/138.0.7204.157/linux64/chromedriver-linux64.zip
[2025-07-16T17:20:12.551+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-07-16T17:20:21.083+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:20:21.955+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/138.0.7204.157]
[2025-07-16T17:20:24.896+0000] {insert_data_to_json.py:20} INFO - ❌ Erreur lors du scraping : Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x557e5edee7da <unknown>
#1 0x557e5e8932e0 <unknown>
#2 0x557e5e8cd7bd <unknown>
#3 0x557e5e8c8ad7 <unknown>
#4 0x557e5e918e9e <unknown>
#5 0x557e5e918466 <unknown>
#6 0x557e5e90a683 <unknown>
#7 0x557e5e8d6b5b <unknown>
#8 0x557e5e8d7f31 <unknown>
#9 0x557e5edb372b <unknown>
#10 0x557e5edb7534 <unknown>
#11 0x557e5ed9a229 <unknown>
#12 0x557e5edb80d8 <unknown>
#13 0x557e5ed7e61f <unknown>
#14 0x557e5eddbdd8 <unknown>
#15 0x557e5eddbfb6 <unknown>
#16 0x557e5ededaf6 <unknown>
#17 0x7ff8dd8c81c4 <unknown>

[2025-07-16T17:20:25.035+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-16T17:20:25.165+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-16T17:20:25.174+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=scrape_and_insert_data_to_json, run_id=scheduled__2025-06-15T00:00:00+00:00, execution_date=20250615T000000, start_date=20250716T172004, end_date=20250716T172025
[2025-07-16T17:20:25.319+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-07-16T17:20:25.322+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-07-16T17:20:25.325+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline queued_at:2025-07-16 17:12:46.679482+00:00
[2025-07-16T17:20:25.328+0000] {logging_mixin.py:190} INFO - Task hostname:569ba507bc01 operator:PythonOperator
[2025-07-16T17:20:25.394+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-16T17:20:25.493+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-16T17:20:25.500+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-07-16T17:30:03.035+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T17:30:03.163+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-15T00:00:00+00:00 [queued]>
[2025-07-16T17:30:03.236+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-15T00:00:00+00:00 [queued]>
[2025-07-16T17:30:03.244+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-07-16T17:30:03.385+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_insert_data_to_json> on 2025-06-15 00:00:00+00:00
[2025-07-16T17:30:03.426+0000] {standard_task_runner.py:72} INFO - Started process 419 to run task
[2025-07-16T17:30:03.441+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'scrape_and_insert_data_to_json', 'scheduled__2025-06-15T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpbnl2hgil']
[2025-07-16T17:30:03.447+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask scrape_and_insert_data_to_json
[2025-07-16T17:30:03.818+0000] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-15T00:00:00+00:00 [running]> on host 569ba507bc01
[2025-07-16T17:30:04.862+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='scrape_and_insert_data_to_json' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-15T00:00:00+00:00'
[2025-07-16T17:30:04.882+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-16T17:30:04.885+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-16T17:30:04.893+0000] {logging_mixin.py:190} INFO - Current task name:scrape_and_insert_data_to_json state:running start_date:2025-07-16 17:30:03.178860+00:00
[2025-07-16T17:30:04.899+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-07-16T17:30:04.912+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-16T17:30:04.932+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-07-16T17:30:08.491+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:30:11.726+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:30:26.821+0000] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/138.0.7204.157/chromedriver-linux64/chromedriver] found in cache
[2025-07-16T17:30:27.705+0000] {insert_data_to_json.py:20} INFO - ❌ Erreur lors du scraping : Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x56252de327da <unknown>
#1 0x56252d8d72e0 <unknown>
#2 0x56252d9117bd <unknown>
#3 0x56252d90cad7 <unknown>
#4 0x56252d95ce9e <unknown>
#5 0x56252d95c466 <unknown>
#6 0x56252d94e683 <unknown>
#7 0x56252d91ab5b <unknown>
#8 0x56252d91bf31 <unknown>
#9 0x56252ddf772b <unknown>
#10 0x56252ddfb534 <unknown>
#11 0x56252ddde229 <unknown>
#12 0x56252ddfc0d8 <unknown>
#13 0x56252ddc261f <unknown>
#14 0x56252de1fdd8 <unknown>
#15 0x56252de1ffb6 <unknown>
#16 0x56252de31af6 <unknown>
#17 0x7f1199f7d1c4 <unknown>

[2025-07-16T17:30:27.709+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-16T17:30:27.741+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-16T17:30:27.744+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=scrape_and_insert_data_to_json, run_id=scheduled__2025-06-15T00:00:00+00:00, execution_date=20250615T000000, start_date=20250716T173003, end_date=20250716T173027
[2025-07-16T17:30:27.833+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-07-16T17:30:27.835+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-07-16T17:30:27.838+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline queued_at:2025-07-16 17:28:10.518425+00:00
[2025-07-16T17:30:27.841+0000] {logging_mixin.py:190} INFO - Task hostname:569ba507bc01 operator:PythonOperator
[2025-07-16T17:30:27.897+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-16T17:30:28.017+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-16T17:30:28.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
