[2025-07-17T10:39:42.072+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-17T10:39:43.400+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.insert_data_to_postgresql manual__2025-07-17T00:17:54.106541+00:00 [queued]>
[2025-07-17T10:39:43.484+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.insert_data_to_postgresql manual__2025-07-17T00:17:54.106541+00:00 [queued]>
[2025-07-17T10:39:43.491+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-07-17T10:39:43.578+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_data_to_postgresql> on 2025-07-17 00:17:54.106541+00:00
[2025-07-17T10:39:43.618+0000] {standard_task_runner.py:72} INFO - Started process 919 to run task
[2025-07-17T10:39:43.633+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'insert_data_to_postgresql', 'manual__2025-07-17T00:17:54.106541+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmp9gj8m0st']
[2025-07-17T10:39:43.643+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask insert_data_to_postgresql
[2025-07-17T10:39:43.894+0000] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.insert_data_to_postgresql manual__2025-07-17T00:17:54.106541+00:00 [running]> on host 569ba507bc01
[2025-07-17T10:39:44.448+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='insert_data_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2025-07-17T00:17:54.106541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-17T00:17:54.106541+00:00'
[2025-07-17T10:39:44.455+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-17T10:39:44.465+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-17T10:39:44.468+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_postgresql state:running start_date:2025-07-17 10:39:43.415174+00:00
[2025-07-17T10:39:44.475+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-07-17T10:39:44.483+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-17T10:39:44.511+0000] {logging_mixin.py:190} INFO - ❌ Échec de la connexion : connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2025-07-17T10:39:44.515+0000] {logging_mixin.py:190} INFO - ❌ Erreur PostgreSQL : Échec de la connexion à la base de données.
[2025-07-17T10:39:44.518+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-17T10:39:44.586+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-17T10:39:44.595+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=insert_data_to_postgresql, run_id=manual__2025-07-17T00:17:54.106541+00:00, execution_date=20250717T001754, start_date=20250717T103943, end_date=20250717T103944
[2025-07-17T10:39:44.772+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-07-17T10:39:44.778+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-07-17T10:39:44.795+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline queued_at:2025-07-17 00:17:54.887499+00:00
[2025-07-17T10:39:44.801+0000] {logging_mixin.py:190} INFO - Task hostname:569ba507bc01 operator:PythonOperator
[2025-07-17T10:39:44.892+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-17T10:39:45.261+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-17T10:39:45.348+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
