[2025-07-16T17:20:04.431+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T17:20:04.483+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-22T00:00:00+00:00 [skipped]>, dependency 'Task Instance State' FAILED: Task is in the 'skipped' state.
[2025-07-16T17:20:04.520+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
[2025-07-16T17:30:02.904+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-16T17:30:03.024+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-22T00:00:00+00:00 [queued]>
[2025-07-16T17:30:03.066+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-22T00:00:00+00:00 [queued]>
[2025-07-16T17:30:03.069+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-07-16T17:30:03.205+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): scrape_and_insert_data_to_json> on 2025-06-22 00:00:00+00:00
[2025-07-16T17:30:03.270+0000] {standard_task_runner.py:72} INFO - Started process 417 to run task
[2025-07-16T17:30:03.291+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bank_reviews_etl_and_analysis_pipeline', 'scrape_and_insert_data_to_json', 'scheduled__2025-06-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_load_reviews.py', '--cfg-path', '/tmp/tmpyr8papgv']
[2025-07-16T17:30:03.297+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask scrape_and_insert_data_to_json
[2025-07-16T17:30:03.595+0000] {task_command.py:467} INFO - Running <TaskInstance: bank_reviews_etl_and_analysis_pipeline.scrape_and_insert_data_to_json scheduled__2025-06-22T00:00:00+00:00 [running]> on host 569ba507bc01
[2025-07-16T17:30:04.745+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mohammed' AIRFLOW_CTX_DAG_ID='bank_reviews_etl_and_analysis_pipeline' AIRFLOW_CTX_TASK_ID='scrape_and_insert_data_to_json' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-22T00:00:00+00:00'
[2025-07-16T17:30:04.757+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-16T17:30:04.766+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-16T17:30:04.770+0000] {logging_mixin.py:190} INFO - Current task name:scrape_and_insert_data_to_json state:running start_date:2025-07-16 17:30:03.027261+00:00
[2025-07-16T17:30:04.772+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline and current dag run status:running
[2025-07-16T17:30:04.781+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-16T17:30:04.800+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-07-16T17:30:08.488+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:30:13.180+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-07-16T17:30:16.799+0000] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/138.0.7204.157/chromedriver-linux64/chromedriver] found in cache
[2025-07-16T17:30:22.246+0000] {insert_data_to_json.py:20} INFO - ‚ùå Erreur lors du scraping : Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
Stacktrace:
#0 0x5594be9947da <unknown>
#1 0x5594be4392e0 <unknown>
#2 0x5594be4737bd <unknown>
#3 0x5594be46ead7 <unknown>
#4 0x5594be4bee9e <unknown>
#5 0x5594be4be466 <unknown>
#6 0x5594be4b0683 <unknown>
#7 0x5594be47cb5b <unknown>
#8 0x5594be47df31 <unknown>
#9 0x5594be95972b <unknown>
#10 0x5594be95d534 <unknown>
#11 0x5594be940229 <unknown>
#12 0x5594be95e0d8 <unknown>
#13 0x5594be92461f <unknown>
#14 0x5594be981dd8 <unknown>
#15 0x5594be981fb6 <unknown>
#16 0x5594be993af6 <unknown>
#17 0x7fb51a8371c4 <unknown>

[2025-07-16T17:30:22.253+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-16T17:30:22.548+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-16T17:30:22.553+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bank_reviews_etl_and_analysis_pipeline, task_id=scrape_and_insert_data_to_json, run_id=scheduled__2025-06-22T00:00:00+00:00, execution_date=20250622T000000, start_date=20250716T173003, end_date=20250716T173022
[2025-07-16T17:30:22.681+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-07-16T17:30:22.683+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-07-16T17:30:22.684+0000] {logging_mixin.py:190} INFO - Dag name:bank_reviews_etl_and_analysis_pipeline queued_at:2025-07-16 17:28:10.915427+00:00
[2025-07-16T17:30:22.686+0000] {logging_mixin.py:190} INFO - Task hostname:569ba507bc01 operator:PythonOperator
[2025-07-16T17:30:22.790+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-16T17:30:22.911+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-16T17:30:22.918+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
